version: '3'

services:
  redis:
    image: redis:alpine
    
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
      
  web:
    build: ./crypto_rate
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db
  
  celery:
    build: ./crypto_rate
    command: celery -A crypto_rate worker -l info
    volumes:
      - ./crypto_rate/:/usr/src/app/
    depends_on:
      - redis
      
  celery-beat:
    build: ./crypto_rate
    command: celery -A crypto_rate beat -l info
    volumes:
      - ./crypto_rate:/usr/src/app/
    depends_on:
      - redis


volumes:
  postgres_data:
